### ISSUE TITLE
Problem with spruce tree not growing in 'Taiga Hills' biome

### ISSUE THREAD

**Issue by staygroovy57** [Civcraft/RealisticBiomes#11]
A while back I did alert devs that spruce had stopped growing in 'Taiga' biomes, thankfully this has now been fixed. But I noticed that "Taiga Hills" is still unable to allow these trees to grow and they definitely used to be growing before. coords are: -11500 -9250 (79)

Could you please edit the config to also allow for "Taiga Hills" to allow spruce growth again? 

Also I am still experiencing problems with acacia not growing in desert biomes, this is at high evelation (Y = 236) ... is there something preventing trees from growing past a certain Y level? I can grow jungle trees at the same elevation in our jungle sky farm.

Thank you.

**Comment by WildWeazel** [comment]
see #8
