### ISSUE TITLE
Prevent fishing without sunlight or underwater

### ISSUE THREAD

**Issue by gipsy-king** [Civcraft/RealisticBiomes#25]
We could prevent fishing when a FishEvent happens in a block not on surface under direct sunlight.

Would it make sense? Would anybody get angry because of this?

**Comment by ttk2** [comment]
probably but not enough for us to care

**Comment by WildWeazel** [comment]
The sunlight thing was the logical way to prevent stacking farms to abuse biome rarity. It doesn't really apply directly to fishing, that would be more like active fishing poles per chunk or something. Really it would make sense to scale fishing to the size of the body of water but that's not an easy calculation.

**Comment by gipsy-king** [comment]
Ok sounds right.
