### ISSUE TITLE
Unsafe script for gh-pages branch

### ISSUE THREAD

**Issue by drjawa** [Civcraft/RealisticBiomes#28]
Hmm, chromium and firefox both complain about unsafe script which has to be manually loaded before the spreadsheet loads. Probably due it being loaded without ssl.

The page: https://civcraft.github.io/RealisticBiomes/spreadsheet/

The branch for the page: https://github.com/Civcraft/RealisticBiomes/tree/gh-pages

I can see this being a barrier to serving its intended purpose...

@gipsy-king any ideas?

**Comment by drjawa** [comment]
I guess for now I'll link the http version, but users of httpseveryhwere will not be pleased.

**Comment by gipsy-king** [comment]
Yea I can fix that quickly.

**Comment by drjawa** [comment]
Seems fixed. Excellent work.
