### ISSUE TITLE
Greenhouse effect problems

### ISSUE THREAD

**Issue by Goldmattress** [Civcraft/RealisticBiomes#32]
Green house effect is heavily broken and it's relation to glow stone negating biome effects as well.

There are also problems with plants like cacti ignoring the need for sunlight.

I'll try and get some video and screenshot evidence of these things.

**Comment by WildWeazel** [comment]
Broken as in bugged or imbalanced? Has something changed recently?

**Comment by ttk2** [comment]
Probably a little of both at this point.

**Comment by Goldmattress** [comment]
As far as I know if the spreadsheet is right it's been broken for a long,
long time.

**Comment by WildWeazel** [comment]
What exactly is wrong with glowstone? The documentation is kind of misleading. When it says "ignore biome" that means that the biome modifier is calculated independently of glowstone, so glowstone _only_ acts as a light source. If that's false, then glowstone _overrides_ the biome and provides a 75% modifier everywhere. There's been some confusion over that point before. We should probably refer to it as "light only" when true.

**Comment by ttk2** [comment]
We should probably clear this up by deciding how we want it to work and fixing it to work like that.

**Comment by gipsy-king** [comment]
@Goldmattress I wrote up some general docs with something about greenhouse: https://github.com/Civcraft/RealisticBiomes/wiki#greenhouse

There are two problems with greenhouse, and when reporting bugs we should aim to distinguish them:

1. Confusing namings and documentation and 2. incorrect/not-ideal behaviour.

IMO the greenhouse effect is way too high for most plants and defeats the purpose of RB.

**Comment by ttk2** [comment]
how much do we have to nerf it then?

**Comment by gipsy-king** [comment]
I would take it down to 25% (was 75%) and/or remove the "ignore biome" flag for almost all plants.

But there would probably be a very heavy opposition from anybody that has any farm in an unnatural biome.

**Comment by WildWeazel** [comment]
Removing "ignore biome" would result in a rate increase in almost all biomes

**Comment by gipsy-king** [comment]
No it would decrease the rate but it wouldn't make sense anyway, only for underground farms. ignore that. Actually, "ignore biome" is always true when there is a greenhouse rate set!

It should be removed since it's not used - it only makes sense for underground farms already in a biome that allows growth.

**Comment by ttk2** [comment]
just remove the setting and rebalance then. Just make RB less of a mess is the main goal.

**Comment by gipsy-king** [comment]
I'm gonna leave this open for the removal of the unused "ignore biome" flag from code.

**Comment by gipsy-king** [comment]
closed for new [growth rate rewrite proposal](https://github.com/Civcraft/RealisticBiomes/issues/42)
