### ISSUE TITLE
add OP command to completely disable growthevents temporarily

### ISSUE THREAD

**Issue by gipsy-king** [Civcraft/RealisticBiomes#37]
@ttk2 the lag is very bad, let's try to temporarily deter people from AFKing.

The command would set a simple flag that cancels all plant growth events for plants, without writing to config or anything complicated, it would get reset on server restart.

If active, all persistent plant growthevents will **always** be cancelled, you would have to relog so that chunks reload to force growth.

What do you think?

**Comment by ttk2** [comment]
lets do it, make it configurable live, but people will just keep AFK'ing anyways, we would have to use this to encourage people to work on the autokicker.

**Comment by gipsy-king** [comment]
closing in favour of just increasing config growth times and working on AFKPGC
