### ISSUE TITLE
Cactus grows without sunlight

### ISSUE THREAD

**Issue by Goldmattress** [Civcraft/RealisticBiomes#38]
Cactus grows without sunlight, even if there is a block above it, it will still grow.

**Comment by gipsy-king** [comment]
That's vanilla. RB penalizes the lack of sunlight but it still grows.

**Comment by Goldmattress** [comment]
No its not look at the config, it inherits column which requires sunlight,
this is a bug.

**Comment by gipsy-king** [comment]
"requires sunlight" means that a penalty is applied, not that it does not grow at all. Cactus also used to grow on civcraft before the update to persistence, just slower. I have a farm with the cacti in columns without **direct** sunlight, I have seen it work.

**Comment by Goldmattress** [comment]
That is absolutely not how it was supposed to work, every bit of documentation has indicated that all columnar plants require sunlight or glow stone to grow. I know very well that it has worked for a long time I just didn't bother to post about it till now.

**Comment by gipsy-king** [comment]
See [here](https://github.com/Civcraft/RealisticBiomes/blame/master/src/com/untamedears/realisticbiomes/GrowthConfig.java#L298) how it was always a penalty. Before that commit I think there was a "openSkyBonus" modifier. So I don't know where you got that it absolutely requires full sunlight to grow.

Here is a screenshot of a vertical cactus farm that is over a year old:
![](http://i.imgur.com/zzdLWeN.jpg?1)
I remember that the builder did the math for not-full-sunlight and space efficiency.

**Comment by ProgrammerDan** [comment]
Given the long history, changing this would be an absolutely enormous nerf,
perhaps two orders of magnitudes for a larger stacked farm.

I'm not in favor of this change, for now, instead we should fix the docs to
reflect actual behavior.

**Comment by gipsy-king** [comment]
Ok closing, in the wiki article I wrote it is clear that lack of sunlight only applies a penalty https://github.com/Civcraft/RealisticBiomes/wiki#light-bonus
