### ISSUE TITLE
RB spreadsheet says .5hr optimal growth for Sugarcane, best i can do is 3 Hour.

### ISSUE THREAD

**Issue by poopdish** [Civcraft/RealisticBiomes#39]
optimal biome: jungle check, 
optimal soil (doesn't need it, but i tired with some clay anyhow): check
optimal sunlight: check
added additional torches: no effect.

still says 3 hours.
swampland is 6 hours

so either the spreadsheet found here is wrong: https://civcraft.github.io/RealisticBiomes/spreadsheet/
or there is something iffy.

**Comment by gipsy-king** [comment]
The spreadsheet is [right](https://github.com/Civcraft/RealisticBiomes/blob/master/config.yml#L189), it seems like the plugin or the config is not up to date on the main server. @drjawa / @ttk2 ?

**Comment by ttk2** [comment]
I just have not updated it yet, I will do so probably with that new meats stuff. Just waiting on documentation for it.

**Comment by gipsy-king** [comment]
closing as the new config seems to be online now
