### ISSUE TITLE
GrowthConfig.getRate rewrite

### ISSUE THREAD

**Issue by gipsy-king** [Civcraft/RealisticBiomes#42]
@WildWeazel @Maxopoly can you check this?
Pseucode as follows:

    rate = base_rate * biome_rate
    // always return if the plant cannot grow in given biome - this eliminates greenhouse_ignore_biome flag
    if rate == 0 then return
    
    if greenhouse_enabled and block_under_greenhouse
    // always apply greenhouse, the player should figure out when to use it
    then rate *= greenhouse_rate
    // get "sun" from plant block if transparent, else from block above
    else if sun < max_sun
    then
        if needs_sunlight
        // exponential penalty inversely proportional to light level
        then rate *= (sun / max_sun)^3
        // not_full_sunlight_modifier can be a boost or a penalty
        rate *= not_full_sunlight_modifier
    
    // there used to be an "irrigated water" check at this point, I think it is not being used for anything
    
    if soil_bonus
    then rate *= 1 + soil_bonus * soil_blocks_found
    
    return rate

**Comment by Maxopoly** [comment]
Multiplying the rate with both the exponential multiplier and the additonal modifier if there is not full sunlight is a bit weird imo, it should be just put into one configurable value.  

Aside from that it looks very solid

**Comment by gipsy-king** [comment]
@Maxopoly that part is from the original function as seen [here](https://github.com/Civcraft/RealisticBiomes/blob/master/src/com/untamedears/realisticbiomes/GrowthConfig.java#L264) (I should have linked that before BTW).

The idea seems to be that the penalty relative to lack of sunlight is applied to all plants equally (except exceptions like netherwarts), and then each plant can have another configurable not-full-sunlight penalty.

The logic of which plants have a greater not-full-sunlight penalty isn't clear to me, but that would be out of scope for this issue.

**Comment by WildWeazel** [comment]
This looks good, if we're doing away with the biome override option.

**Comment by ttk2** [comment]
looks good to me too.

**Comment by ttk2** [comment]
ok so if this looks good could we implement it?

**Comment by Maxopoly** [comment]
I guess so. I can just make some java code out of the pseudo code gipsy wrote out, tomorrow, if noone else wants to do it.

**Comment by ttk2** [comment]
sound good.

**Comment by gipsy-king** [comment]
closed by @Maxopoly in a0667be
