### ISSUE TITLE
Oak trees bug

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/RealisticBiomes#61]
I already brought this up a while ago on the forum, but it seems like it got lost. Oak trees can grow in just a few minutes, it doesn't seem like their growth events are cancelled at all, I was not able to observe the same behavior for other trees. 
They still grow persistent and I've had cases, where I removed saplings, but the tree grew later anyway at the same spot.

@gipsy-king

**Comment by ttk2** [comment]
yup this is important, we are not canceling growth events right.

**Comment by ProgrammerDan** [comment]
Worth adding here I was forwarded a screenshot last night to indicated trees were growing *next to saplings* instead of replacing the saplings. There was a claim that this only occurs when TPS is bad. I'm not sure how they would be related, but figured I'd relay that information here.

**Comment by gipsy-king** [comment]
@Maxopoly does this always happen, or in some uncertain conditions?

**Comment by Maxopoly** [comment]
The random growth? Afaik always.

**Comment by gipsy-king** [comment]
@ProgrammerDan coud you forward that screenshot to me?

**Comment by ProgrammerDan** [comment]
@gipsy-king It's so buried in my history as to be inaccessible. I'll see if I can remember who sent it to me in the first place and get it again.

**Comment by gipsy-king** [comment]
Ok, thanks!
