### ISSUE TITLE
Spruce trees not growing properly in Ice Mountains

### ISSUE THREAD

**Issue by meowcoolcat** [Civcraft/RealisticBiomes#62]
I've been having many issues with spruce trees growing in the ice mountains near my city.  Both the large and small ones seem to be having issues.  They've all have been planted for 8+ hours and only some are growing yet others are not in the same conditions.

@gipsy-king

**Comment by WildWeazel** [comment]
https://github.com/Civcraft/RealisticBiomes/issues/7

**Comment by gipsy-king** [comment]
Please try with more space around and report back.

**Comment by gipsy-king** [comment]
@WildWeazel they should grow in ice and mountains, per [spreadsheet](https://civcraft.github.io/RealisticBiomes/spreadsheet/).

**Comment by gipsy-king** [comment]
@meowcoolcat any news on this?

**Comment by meowcoolcat** [comment]
@gipsy-king Completely forgot about this.  Will check right now and report back what I see.

**Comment by gipsy-king** [comment]
No problemo, thanks!

**Comment by meowcoolcat** [comment]
@gipsy-king They're all pretty well spaced out and have half slabs around them to block the snow which would stop them from growing.  Seems like 15-20% of the ones I have planted have grown.  Some have after the initial 8 hour grow time but the majority still have not.

**Comment by gipsy-king** [comment]
Seems like leaves were blocking growth
