### ISSUE TITLE
[RealisticBiomes] [SEVERE] Cannot get world id for UUID

### ISSUE THREAD

**Issue by Colonization** [Civcraft/RealisticBiomes#67]
For whatever reason, every RealisticBiomes I install, spams this error in my console:

> 06.01 22:38:52 [Server] INFO [RealisticBiomes] [SEVERE] Cannot get world id for UUID: f78661a0-2b50-42a7-95c3-f9096a43ea6d

I've attempted including it to the database that NameLayer & Citadel are connected to, as well as creating it's own user and database, hoping that'd solve the issue. It didn't. 

It appears to only start spamming the console when a reload is initiated, otherwise, everything is golden and works flawlessly.

**Comment by rourke750** [comment]
We don't support the /reload command and you shouldn't use it.  Try updating to the newest version as well.

**Comment by Colonization** [comment]
I generally don't, but it's makes things quicker when modifying things on the test server. Also, I am using the latest version.

**Comment by rourke750** [comment]
What version are you using?

**Comment by Colonization** [comment]
Version 1.0.4, build #35.

**Comment by rourke750** [comment]
Look for other stacks, but yea just don't use /reload :P

**Comment by Colonization** [comment]
Will do, thanks :)

**Comment by 3ssej** [comment]
I have the same problem...

**Comment by erocs** [comment]
I believe RB is deprecated and https://github.com/DevotedMC/CropControl is the next new thing.

**Comment by ProgrammerDan** [comment]
CropControl is meant to live alongside RB -- it doesn't control crop growth, just drops.... so far :P

**Comment by Maxopoly** [comment]
@3ssej This will only occur if you somehow messed with things, wiping all your realistic biome related databases/tables should fix it.

**Comment by 3ssej** [comment]
I didn't mess with anything, just installed it. Also, I found an updated version of this plugin.
