### ISSUE TITLE
Spreadsheet is outdated or incorrect

### ISSUE THREAD

**Issue by gipsy-king** [Civcraft/RealisticBiomes#83]
...I assume, since the link is striked out in the subreddit sidebar.

I would like to update/fix the spreadsheet at https://civcraft.github.io/RealisticBiomes/spreadsheet

I hope the server admins can answer a few question:
1. Is there still one global config, now for all shards?
2. If not, are the configs accessible through github or similar, with an HTTP request?

If it's not possible to load the configs publicly, do you think it is worthwile to add some kind of static HTML generator, so that we/you can generate a spreadsheet?

Or do you think there shouldn't be an official spreadsheet?

**Comment by ProgrammerDan** [comment]
Each shard is unique.

Our intent is that players will discover the best shards for each crop / animal, and over time a player-generated understanding of the worlds will be formed.

At least at present we have no intention of releasing the "official" RB configs for each shard.

**Comment by gipsy-king** [comment]
Ok, thanks!

**Comment by ProgrammerDan** [comment]
No problem :) Happy discovering!
