### ISSUE TITLE
Cactus and sugar cane growth is bugged

### ISSUE THREAD

**Issue by Aleksey-Terzi** [Civcraft/RealisticBiomes#87]
Original problem description: https://www.reddit.com/r/Civcraft/comments/51895l/cactus_growth_bugged/  

Problem is that cactus and sugar cane are not growing as specified in RB config. Some plants are maturing in time - other maturing much much later than expected.

Example with sugar cane:

- when sugar cane first time planted - on harvest I have all sugar cane matured
- when I cut 2nd and 3rd sugar cane blocks and leave 1st block - after time will be matured only 1/2 or 1/3 of what is supposed, the rest will grow much later.

The only solution - break all sugar cane blocks and replant them each time on harvest

**Comment by gipsy-king** [comment]
This has to be investigated further.

I think it's worth looking into why it is that BlockBreakEvents don't check for column-type plants in https://github.com/Civcraft/RealisticBiomes/blob/master/src/com/untamedears/realisticbiomes/listener/GrowListener.java#L299 so probably the time simply isn't reset until next chunk load event.

**Comment by BlackXnt** [comment]
@gipsy-king The BlockBreakEvents seem to only be used for pumpkins and melons. From a quick testing I have done in-game sugar canes do seem to restart the growth timer when breaking the top part of the plant without reloading the chunk.

**Comment by gipsy-king** [comment]
@BlackXnt right click with stick also restarts the growth, did you take that into account?

**Comment by Aleksey-Terzi** [comment]
Also want to draw attention that problem somehow related to water spots or slabs placed above.  
Matured/not matured sugar cane looks like alternated by diagonal line along water spots.

**Comment by BlackXnt** [comment]
@gipsy-king No I didn't. If that's the case your assumption is probably correct. I couldn't find anything else in the code that will reset the growth timer if you only break the top part. Weird no one noticed this in 2.0.

**Comment by gipsy-king** [comment]
@BlackXnt perhaps because piston break event *do* (or should by the code) reset the stage, and in 2.0 everybody had full autofarms...

**Comment by gipsy-king** [comment]
@Aleksey-Terzi this is really strange, surrounding blocks are not checked by RB for sugarcane.

**Comment by gipsy-king** [comment]
Seems to be fixed by #88
